title: Andrea Wayte
description: All about me
author: Andrea Wayte
github: https://github.com/andreasandpiper
about: Maker of many things. Fabric hoarder. Clothing maker. Program in Ruby & JS

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/andreasandpiper"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/andrea-wayte/"
    - icon: fa-github
      link: "https://github.com/andreasandpiper"

share:
  twitter_username: andreasandpiper
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://andreasandpiper.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
